// @ts-nocheck
import { Router } from "express";
import auth from "./auth/auth.routes.js";
import users from "./users/users.routes.js";
import categories from "./categories/categories.routes.js";
import products from "./products/products.routes.js";
import cart from "./cart/cart.routes.js";
import vouchers from "./vouchers/vouchers.routes.js";
import deliveryZones from "./delivery-zones/delivery-zones.routes.js";
import orders from "./orders/orders.routes.js";
import payments from "./payments/payments.routes.js";
import refunds from "./refunds/refunds.routes.js";
import production from "./production/production.routes.js";
import deliveries from "./deliveries/deliveries.routes.js";
import inventory from "./inventory/inventory.routes.js";
import kasir from "./kasir/kasir.routes.js";
import expenses from "./expenses/expenses.routes.js";
import reviews from "./reviews/reviews.routes.js";
import notifications from "./notifications/notifications.routes.js";
import dashboard from "./dashboard/dashboard.routes.js";
import settings from "./settings/settings.routes.js";
import auditLogs from "./audit-logs/audit-logs.routes.js";

const router = Router();
router.use("/auth", auth);
router.use("/users", users);
router.use("/categories", categories);
router.use("/products", products);
router.use("/cart", cart);
router.use("/vouchers", vouchers);
router.use("/delivery-zones", deliveryZones);
router.use("/orders", orders);
router.use("/payments", payments);
router.use("/refunds", refunds);
router.use("/production", production);
router.use("/deliveries", deliveries);
router.use("/inventory", inventory);
router.use("/kasir", kasir);
router.use("/expenses", expenses);
router.use("/reviews", reviews);
router.use("/notifications", notifications);
router.use("/dashboard", dashboard);
router.use("/settings", settings);
router.use("/audit-logs", auditLogs);
export default router;
